### ISSUE TITLE
Segment Offset values < 1

### ISSUE THREAD

**Issue by PaulH74** [otakudaddy/smartstory_issue_tracker#1]
Entering a segment offset value < 1 results in an invalid output float value containing multiple decimal points.

Eg: Offset value 0.5 sec => 0.5.0

![offset_issue_01a](https://user-images.githubusercontent.com/21220682/52244604-864fef80-2932-11e9-8736-cb0e3021de60.JPG)
![offset_issue_01b](https://user-images.githubusercontent.com/21220682/52244605-864fef80-2932-11e9-9689-84b320146b27.jpg)
![offset_issue_01c](https://user-images.githubusercontent.com/21220682/52244606-86e88600-2932-11e9-98dc-9e51b9e86c88.jpg)

**Comment by otakudaddy** [comment]
Hi Paul,

I've deployed a fix, please confirm
Cheers,
Charlie

**Comment by PaulH74** [comment]
Hi Charlie,

Still have the problem - although the segment offset shows the correct float value, the true value in (XML?) is still showing an invalid float.

Please see screen shots below...

![image](https://user-images.githubusercontent.com/21220682/52308449-71866100-29f1-11e9-84a5-90c503b0565f.png)

![image](https://user-images.githubusercontent.com/21220682/52308478-882cb800-29f1-11e9-8430-de1533ec8bfb.png)

**Comment by otakudaddy** [comment]
![ssml](https://user-images.githubusercontent.com/3423580/52309806-5e759000-29f5-11e9-9ad6-4ded0832a2cf.png)
it seems to be working for me... can you try to refresh/empty cache?
Cheers,
Charlie

**Comment by PaulH74** [comment]
Hi Charlie, 

Yes you are correct - it was a cache issue at my end.  

I've just refreshed the cache and working correctly.

Sorry for the confusion.
